# Travis configuration.  Build the simulator and run its tests.

env:
  global:
    - secure: "XbmV86GSZzwP7MhgcJolpVisvGnB3Rc6iffd0rhTu7ZXDc/ntmXDIvuO1ZYISGkKlQtQ5CQA2wMwMfO1rOggIy30bI3GnDh75E8n55nkrmVtDIRYnP6ABxTMGuPljU8gafcE1VKY331ey1+BGD/4879OBDI8kGXrcCjse6NwjdJELmFZAqcTlXA0wkzUlLRVeELiJizRybd30kmmhVmuDszpQ5TDwcxHJu7TsHQjVJBdpfoP/SIxAPdZBDQ42sRbYiBlE9SDmkVdBPxYvlyQG8aRv7YzP1JzWtlWg+o6CB611tO9OgIpoAOAgq82lWaA0XX/P4KRGgC8CIS4JwQc8SuA1HxLY/nQSl1vhMjQhlBpShTllFBNaaDA6227y9D+gfb27lbmMb/FZ0elTo2ltyeoYLoR7/odauFtOIO3SaxpnEnGdDBmh+KiLazzWEvix5IO5O7dYDyGuQFag0/kfHflBeLSVAPXDBfw/sGJATQERH+D3Ab4GVot/+BFvAeCUakM7GS3KjzQdA/U5+4G2aDLmDWNGo6ZjTGrWiMtAJVRx++RKmLh67s/W4rOlma+XZmFiLOgmov2RuGAuPNrPiBfuNaoGFynjwGPZeBwxlu2AWzIgFCAHelJD5Xf5nyClTPPyDSJj3doHSJBJAJpg0xnU66aADlmS5Doka3u5Gg="

addons:
  coverity_scan:
    project:
      name: runtimeco/mcuboot
      version: 1.0
      description: Secure boot for 32-bit Microcontrollers!
    notification_email: utzig@apache.org
    build_command: make -f Makefile.coverity
    branch_pattern: coverity_scan
