# Travis configuration.  Build the simulator and run its tests.

language: rust

cache:
  directories:
    - $HOME/TOOLCHAIN
    - cargo

matrix:
  include:
    # Runs each value defined in $SINGLE_FEATURES by itself in the order
    # the were defined.
    - os: linux
      env: SINGLE_FEATURES="sig-ecdsa sig-ed25519 enc-kw bootstrap" TEST=sim
    - os: linux
      env: SINGLE_FEATURES="none sig-rsa sig-rsa3072 overwrite-only validate-primary-slot" TEST=sim
    - os: linux
      env: SINGLE_FEATURES="enc-rsa" TEST=sim

    # Values defined in $MULTI_FEATURES consist of any number of features
    # to be enabled at the same time. The list of multi-values should be
    # separated by ',' and each list of values is run sequentially in the
    # defined order.
    - os: linux
      env: MULTI_FEATURES="sig-rsa overwrite-only,sig-ecdsa overwrite-only" TEST=sim
    - os: linux
      env: MULTI_FEATURES="sig-rsa validate-primary-slot,sig-ecdsa validate-primary-slot" TEST=sim
    - os: linux
      env: MULTI_FEATURES="enc-kw overwrite-only,enc-rsa overwrite-only" TEST=sim
    - os: linux
      env: MULTI_FEATURES="sig-rsa enc-rsa validate-primary-slot" TEST=sim
    - os: linux
      env: MULTI_FEATURES="sig-rsa enc-kw validate-primary-slot bootstrap" TEST=sim
    - os: linux
      env: MULTI_FEATURES="sig-ecdsa enc-kw validate-primary-slot" TEST=sim

    # FIXME: this test actually fails and must be fixed
    #- os: linux
    #  env: MULTI_FEATURES="sig-rsa validate-primary-slot overwrite-only"

    - os: linux
      language: go
      env: TEST=mynewt
      go:
        - "1.11"

before_install:
  - |
    if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
      ./ci/check-signed-off-by.sh
      if [ $? -ne 0 ]; then
        exit 1
      fi
    fi

install:
  - ./ci/${TEST}_install.sh

script:
  - ./ci/${TEST}_run.sh

notifications:
  slack:
    rooms:
      - secure: "Tg9ZvJfb6e4QSEsxUvwW2MIqbuNRxD4nAOkgs8eopj/fRtqN6Zk06NVSeMmYcZunDFJXUSzYANBsF98OtaaUlm4WVt2T0ZFBJZrOYfIv18/zXCjYa04sDxur57F1ZYTYKyRpdUkfzPd/rGE4jKLQNcia+r/BTQbJkcZbXeg5/6cUeMP1so8/o0oMhSQP+GH0fLbyLzx3VPE8zu6+j2fCFC7R3idxtfO9VtsKlubfi3HgPgXTs+DEAAA8aoOku2esjFSFXTtdUFGz90YzyShZvtMcRg3Grp9+PZAsJwWk4eKSonKCO0DScfPUlMZbJcV7VsmyTxYKLLsGRZae6ZBH+XLfx5XeqgtgCor3FYx2dUXYfV9y8VvERDdossB0gZ/V2OUGePctDefiORytV6dMa7X3AfSdosgs/tjG4kbf+PMaVULzwF6dd3CdsxdClSl68UQPWA6wC2TEyo1EQea8jgZU6heLustZaQZhBkFkr/6j75XeGBjPw2fgVRkgg/OnTOYmo7N8181wOU+xORIEO1BtYmgRpc0cgpm4H9457diSHG1D2SoNy4tiQPCW2enN00QNGK5pZSL/FGA/ReUcALgAW0QcOljjU2bUSGPxo/VAi5ZyljWgVAGQ5qHJ4jgdfPf7VJUzCVH64G1S5+0gZPpO6vvvPdZtqeXrfBZMOBw="
    on_success: always
