[package]
name = "bootsim"
version = "0.1.0"
authors = ["David Brown <davidb@davidb.org>"]

[build-dependencies]
gcc = "0.3.38"

[dependencies]
libc = "0.2.0"
rand = "0.3.0"
docopt = "0.6"
rustc-serialize = "0.3"
log = "0.3"
env_logger = "0.3"
simflash = { path = "simflash" }
mcuboot-sys = { path = "mcuboot-sys", features = ["sig-rsa"] }
bitflags = "0.9"
ring = { version = "0.11", features = ["rsa_signing"] }
untrusted = "0.5"
pem = "0.4"

[profile.test]
opt-level = 1
