[package]
name = "bootsim"
version = "0.1.0"
authors = ["David Brown <davidb@davidb.org>"]
build = "build.rs"

[build-dependencies]
gcc = "0.3.38"

[dependencies]
libc = "0.2.0"
rand = "0.3.0"
docopt = "0.6"
rustc-serialize = "0.3"
log = "0.3"
env_logger = "0.3"
simflash = { path = "simflash" }
enumflags = "0.1"
enumflags_derive = "0.2"
rust-crypto = "0.2"

[profile.test]
opt-level = 1
