# For development, trigger this on any push.
on: [push, pull_request]

jobs:
  environment:
    name: Mynewt build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Print the environment
      run: |
        uname -a
        lscpu
        free
        pwd
    - name: Mynewt install
      run: |
        ./ci/mynewt_install.sh
    - name: Mynewt run
      run: |
        ./ci/mynewt_run.sh
