# For development, trigger this on any push.
on: [pull_request]

jobs:
  environment:
    name: Mynewt build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Print the environment
      run: |
        uname -a
        lscpu
        free
        pwd
    - name: Signed commit check
      run: |
        ./ci/check-signed-off-by.sh
    - name: Mynewt install
      run: |
        ./ci/mynewt_install.sh
    - name: Mynewt run
      run: |
        ./ci/mynewt_run.sh
